UPDATE PLANO SET VALOR = VALOR * 1.1 WHERE DESCRICAO LIKE '%Básico%';
UPDATE PLANO SET VALOR = VALOR * 1.05 WHERE DESCRICAO LIKE '%Executivo%';
UPDATE PLANO SET VALOR = VALOR * 1.03 WHERE DESCRICAO LIKE '%Master%';
SELECT * FROM PLANO;